### ISSUE TITLE
Scrips::Out of office message

### ISSUE THREAD

**Issue by margaret-bywater** [bywatersolutions/rtenhancements#10]
Create a script to send an automatic/generic "<Owner> is out of the office" message when a partner replies to a ticket and the <Owner>'s messaging preferences are set to suspended. 

First I'd like to determine what the generic message should be. Drafts now being accepted

**Comment by margaret-bywater** [comment]
Talked about this with Kyle and Donna.

We do need a notice of some sort to send t the partners who don't typically log into RT and just use email. It should also be posted in the ticket history for CYA.

We've got a basic template created. We started on the scrips, but should the perl be in the user defined condition or part of the action?

**Comment by donnabws** [comment]
Hello,
Your response to this ticket has been received.  I am currently out of the office and will not be able to respond.  If this requires immediate attention, please either call Support at 888.900.8944 or email support@bywatersolutions.com.
Thank you!


(And I know I am asking for the moon, but it would be awesome to be able to customize it to include a date of return.)

**Comment by margaret-bywater** [comment]
Not the moon perse, but it's more complicated. 
The 'how to do it' is part of the question that we've not progressed past. I think Barton and i have arrived at using a USER custom field that like
`[ ] check this box if you are out of the office`
That would be a setting to click in your RT account page. 

A few solutions might work.

1) to have a custom scripts for each user, whose templates you update with the text your want used, including the date. But would you want to be customizing another away message like that? 
2) more custom fields with that date range or free text that you want put into the email notification that goes out.

**Comment by margaret-bywater** [comment]
Okay, for expediency we're going to go with a User CustomField "Out Of The Office". When leaving for vacation or training a staff member will:
1) Click "Logged in as <Name>". this brings them to their general user summary
2) Click **Edit** to edit their info
3) At the CustomField "Out Of The Office" click the radio button that says "OUT"
4) Save changes. 
That's four clicks and takes seconds to do/undo.

TODO: Work with Brendan to write a scrip that sends the above away messages when the CustomField "Out Of The Office" is active. right now the button does nothing. 

TODO2: with API integration we may be able to have this trigger off google calendar, slack or gmail's away settings, removing the need to flip a switch in RT. TBD.

**Comment by margaret-bywater** [comment]
Also 
- send a notification to the support leads? 
- maybe it reassigns the ticket to ...
- sets the Help Meeting ticket CF to something that's easy to query and have team members monitor. 
- Find some time with Kyle. #Turtle.
