### ISSUE TITLE
Add RT::Extension::GroupSummary

### ISSUE THREAD

**Issue by margaret-bywater** [bywatersolutions/rtenhancements#3]
RT::Extension::GroupSummary - This module allows RT to display semantic information about any group, mainly through CustomFields attached to this group.

It displays information about a group on a Group Summary page, similar to what is done about a user. A Group Summary page includes the name, the description and CustomFields of a group. The Group Summary page can be accessed from any tabs of Admin/Groups and is linked to any display of a principal which is a group (just like any display of a principal which is a user is linked to the related User Summary page).

This module also provides a Group Summary Search feature and links results to related Group Summary pages.

In a future revision, it is planned to use Portlets in a Group Summary page, just like in a User Summary page.

https://metacpan.org/pod/RT::Extension::GroupSummary

**Comment by margaret-bywater** [comment]
Ext added to the Test site and functioning!

**Comment by tgoatley** [comment]
Margaret, the summary is great! We talked about it but I thought I'd bring it up again... it'd be great if there was more summary info like the main contact, phone number & email,  list of group members, even a list of current (hyperlinked ticket numbers and subject?). Wow, easy to get outta control ;~) Looks good!!!

**Comment by bartonski** [comment]
I've written up the steps for installing on the *RT Test Docker* page on the wiki.

**Comment by margaret-bywater** [comment]
Okay!

We've installed the extension on Production RT
We've applied the callback written in test
We added the CSS form test to hide the old groups section
Now we're populating the links for the most annoying to find accounts into RT by hand, until we automate the process. 

Calling this issue closed!
